version: "3.3"
services:
  kapowarr:
    container_name: kapowarr
    environment:
      - "PGID=1000"
      - "PUID=1000"
    image: mrcas/kapowarr:latest
    volumes:
      - "kapowarr-db:/app/db"
      - "/path/to/download_folder:/app/temp_downloads"
      - "/path/to/root_folder:/comics-1"
    ports:
      - 5656:5656

volumes:
  kapowarr-db: