# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

ENV PUID 1000
ENV PGID 1000

USER PUID:PGID

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

CMD [ "python3", "/app/Kapowarr.py" ]
