blank_issues_enabled: false
contact_links:
  - name: Documentation Hub
    url: https://casvt.github.io/Kapowarr/
  - name: Discord
    url: https://discord.gg/5gWtW3ekgZ
  - name: Reddit
    url: https://www.reddit.com/r/kapowarr/
